version: "3.8"
services:
    mongodb:
        image : mongo
        container_name: mongodb
        environment:
            - PUID=1000
            - PGID=1000
        volumes:
            - /Users/jimmy/Dev/nodejs/udemy-edwin-diaz/mongodb/database:/data/db
        ports:
            - 27017:27017
        restart: unless-stopped


# docker exec -it mongodb bash